# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'victor.osorio'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Pet Projects
    submenu:
      - name: CSV Viewer
        link: /projects/csv-viewer
      - name: Plain Test
        link: /projects/plain-test
  - name: Presentations
    submenu:
      - name: "Kafka: Uma introdução para Desenvolvedores e Arquitetos"
        link: /presentations/2020-03-26-sou-java-Kafka
      - name: "Usando Java CDI em projetos Jakarta EE ou Microprofile"
        link: /presentations/2019-09-14-sou-java-cdi
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/vepo
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/victorosorio
      - name: Twitter
        icon: twitter
        link: https://twitter.com/vepo
    
